scara:
  # Publicar todos los estados de las articulaciones
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Controladores de Posición
  j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_link_01
    pid: {p: 1000.0,i: 2.0,d: 1.2}

  # Controladores de Posición
  j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_01_link_02
    pid: {p: 1000.0,i: 2.0,d: 1.2}

  j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_02_link_03
    pid: {p: 1000.0,i: 2.0,d: 1.2}
